config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new'
  get '/cocktails/:id', to: 'cocktails#show', as: :cocktail

  post '/cocktails', to: 'cocktails#create'


  get '/cocktails/:cocktail_id/doses/new', to: 'doses#new', as: :doses
  post '/cocktails/:cocktail_id/doses', to: 'doses#create', as: :cocktail_doses
  delete '/doses/:id', to: 'doses#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true, allow_blank: false
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true, allow_blank: false
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true, allow_blank: false
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new(params[:cocktail])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(params[:dose])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<<div class="container-index">
  <div class="left-side">
    <div class="sticky">
      <div class="button-div">
        <%= link_to "Add a new cocktail", cocktails_new_path, class: "btn-cocktails" %>
      </div>
    </div>
  </div>
  <div class="left-side">
    <div class="container-fluid">
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="card-cocktails col-xs-8 col-md-5">
            <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h1>My Cocktails</h1>
<% @cocktails.each do |cocktail| %>

  <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>

<% end %>

<h3><%= link_to "Make a new cocktail!", cocktails_new_path %></h3>

app/views/cocktails/new.html.erb
<% @cocktail = Cocktail.new %>

<%= form_for @cocktail do |f| %>
  <%= f.label :name, "Enter a name:" %>
  <%= f.text_field :name %>

  <%= f.submit class: "btn btn primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Details Page(<%=@cocktail.name%>)</h1>

  <h3><%= link_to "Put a dose in this cocktail!", doses_path(@cocktail) %></h3>

app/views/doses/new.html.erb
<% @dose = Dose.new %>

<%= form_for [@cocktail, @dose] do |f| %>
  <%= f.label :description, "Enter a description:" %>
  <%= f.text_field :description %>

  <%= f.submit class: "btn btn primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>